# Generated by Django 3.1.1 on 2021-04-07 19:57

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('patrimonio', models.CharField(max_length=15, unique=True)),
                ('dual_boot', models.BooleanField(default=False)),
                ('funciona', models.BooleanField(default=True)),
                ('processador', models.CharField(choices=[('I2', 'Intel Core 2 Duo'), ('I3', 'Intel I3'), ('I5', 'Intel I5'), ('IP', 'Intel Pentium Dual Core')], default='I2', max_length=2)),
                ('hd', models.CharField(choices=[('100GB', '100GB'), ('200GB', '200GB'), ('300GB', '300GB'), ('400GB', '400GB'), ('500GB', '500GB')], default='100GB', max_length=5)),
                ('ram', models.CharField(choices=[('1GB', '1GB'), ('2GB', '2GB'), ('3GB', '3GB'), ('4GB', '4GB')], default='1GB', max_length=3)),
                ('qnt_manutencao', models.IntegerField(default=0)),
                ('em_manutencao', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('color', models.CharField(max_length=7, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('qnt_computador', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('masp', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contato', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('versao', models.CharField(max_length=15)),
                ('tipo', models.CharField(choices=[('SL', 'Software Livre'), ('SP', 'Software Licenciado')], default='SL', max_length=2)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoReserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('F', 'Visualizada')], default='P', max_length=1)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('date_visualizacao', models.DateTimeField(auto_now=True)),
                ('observacao', models.TextField(blank=True)),
                ('arquivo', models.FileField(upload_to=core.validators.path_and_rename, validators=[core.validators.validate_file_extension, core.validators.validate_file_size])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evento', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=7, unique=True)),
                ('responsavel', models.CharField(max_length=100)),
                ('contato', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('start_day', models.DateField()),
                ('end_day', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.curso')),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.disciplina')),
                ('laboratorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.laboratorio')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Em Curso', 'Em Curso'), ('Resolvido', 'Resolvido')], default='Em Curso', max_length=9)),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('pc_codigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.computador')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('evento', models.CharField(max_length=200)),
                ('responsavel', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contato', models.CharField(blank=True, max_length=15)),
                ('computador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.computador')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='computador',
            name='laboratorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.laboratorio'),
        ),
        migrations.AddField(
            model_name='computador',
            name='software',
            field=models.ManyToManyField(to='core.Software'),
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dia', models.CharField(choices=[('1', 'Segunda'), ('2', 'Terça'), ('3', 'Quarta'), ('4', 'Quinta'), ('5', 'Sexta'), ('6', 'Sabado'), ('7', 'Domingo')], max_length=1)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('start_day', models.DateField()),
                ('end_day', models.DateField()),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.curso')),
                ('disciplina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.disciplina')),
                ('laboratorio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.laboratorio')),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.professor')),
            ],
        ),
    ]
