# Generated by Django 3.1.1 on 2020-10-29 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='computador_id',
            new_name='computador_codigo',
        ),
    ]
