# Generated by Django 3.1.1 on 2021-02-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='computador_codigo',
            new_name='computador',
        ),
        migrations.AlterField(
            model_name='computador',
            name='hd',
            field=models.CharField(choices=[('100GB', '100GB'), ('200GB', '200GB'), ('300GB', '300GB'), ('400GB', '400GB'), ('500GB', '500GB')], default='100GB', max_length=5),
        ),
        migrations.AlterField(
            model_name='computador',
            name='patrimonio',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='computador',
            name='processador',
            field=models.CharField(choices=[('I2', 'Intel Core 2 Duo'), ('I3', 'Intel I3'), ('I5', 'Intel I5'), ('IP', 'Intel Pentium Dual Core')], default='I2', max_length=2),
        ),
        migrations.AlterField(
            model_name='computador',
            name='ram',
            field=models.CharField(choices=[('1GB', '1GB'), ('2GB', '2GB'), ('3GB', '3GB'), ('4GB', '4GB')], default='1GB', max_length=3),
        ),
        migrations.AlterField(
            model_name='curso',
            name='name',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='customusuario',
            name='masp',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='name',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='name',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
