# Generated by Django 3.1.1 on 2020-10-09 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='id',
            field=models.IntegerField(default=1557, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='id',
            field=models.IntegerField(default=7265, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='id',
            field=models.IntegerField(default=602675, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='id',
            field=models.IntegerField(default=6573, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='curso_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.curso'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='disciplina_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.disciplina'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='laboratorio_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.laboratorio'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='professor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.professor'),
        ),
        migrations.AlterField(
            model_name='software',
            name='id',
            field=models.IntegerField(default=96237, primary_key=True, serialize=False),
        ),
    ]
