# Generated by Django 3.1.1 on 2020-11-17 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201029_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='computador',
            name='em_manutencao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='computador',
            name='qnt_manutencao',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='log',
            name='categoria',
            field=models.CharField(choices=[('MN', 'Manutenção'), ('AT', 'Atualização'), ('IT', 'Instalação'), ('CR', 'Cadastro'), ('RV', 'Reserva'), ('EM', 'Empréstimo'), ('AS', 'Atualização Status'), ('NS', 'Nova Solicitação')], max_length=2),
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Em Curso', 'Em Curso'), ('Resolvido', 'Resolvido')], max_length=9)),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_fim', models.DateField()),
                ('descricao', models.TextField()),
                ('pc_codigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.computador')),
            ],
        ),
    ]
