# Generated by Django 3.1.1 on 2020-11-17 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201117_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencao',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='status',
            field=models.CharField(choices=[('Em Curso', 'Em Curso'), ('Resolvido', 'Resolvido')], default='Em Curso', max_length=9),
        ),
    ]
