# Generated by Django 3.1.1 on 2020-11-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201117_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencao',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
